services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    expose:
      - "9292"
    env_file:
      - path: ./backend/.env
        required: false
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-https://stickers.hackclub.com}

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    expose:
      - "3000"
    environment:
      ORIGIN: ${ORIGIN:-https://stickers.hackclub.com}
      BACKEND_URL: ${BACKEND_URL:-http://backend:9292}
    depends_on:
      - backend
